### ISSUE TITLE
Implementazione classe Sponsor

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/tcoo#11]
La classe, che estende DomainEntity (vedere issue #8) rappresenta per l'appunto uno sponsor dell'evento. L'attività in questione consiste nel: 

- creare la classe nel progetto proloco-domain-model
- creare degli attributi. A me vengono in mente solo questi:

name: di tipo String e che rappresenta il nome dello sponsor
logo: di tipo String che contiene il nome dell'immagine del logo
description: breve descrizione dell'attività (String)
amount: di tipo double, che rappresenta i soldi che lo sponsor ha dato per l'evento

**Comment by Mistcoding** [comment]
Fatto, se va bene cosi si può chiudere.

**Comment by agazzarini** [comment]
+1 per me
