### ISSUE TITLE
Applicazione web minimale

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/tcoo#13]
Creo una pagina con un semplice form per inserire un evento.

**Comment by gmm89** [comment]
Quando serve, puoi contarmi per lavori con codice HTML o CSS

Date: Fri, 27 Mar 2015 04:26:59 -0700

**Comment by agazzarini** [comment]
Ok, al momento ho inserito una pagina brutta a morire, con dentro 1 form 
e basta, nient'altro, giusto per far vedere tutto il giro.

**Comment by ubdesign** [comment]
Siamo solo io e te che gia ci lavoriamo... Quindi lo faremo io e te penso
Il 27/mar/2015 13:41 "Andrea Gazzarini" <notifications@github.com> ha
scritto:
