### ISSUE TITLE
implementazione Classe User

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/tcoo#2]
Un'altra classe di cui sicuramente necessiteremo sarà la classe User, che incapsula, come immaginate, il concetto di utente.

Da definire se vogliamo fare 

- una classe user con all'interno un attributo che indica la tipologia dell'utente 
- una classe specifica per ogni tipologia di utente. E.g. (Admin, EndUser, StandUser)  

A tal proposito vedetevi la chiacchierata che abbiamo fatto sulla issue #1, nata da uno spunto suggerito da @gmm89

**Comment by agazzarini** [comment]
Per adesso è meglio fare una sola classe di nome User con all'interno (oltre gli attributi che dicevamo ieri) un nuovo attributo di tipo int che indica il tipo dell'utente 

1 = admin (utente della proloco)
2 = end user (utente pubblico)
3 = stand user (proprietario dello stand)

Il progetto di riferimento è proloco-domain-model, il package è it.proloco.dm.user (nuovo, sottopackage dell'attuale it.proloco.dm) 

Per creare il nuovo package click col tasto destro sul package it.proloco.dm >> New >> Package

**Comment by bluegrifer00** [comment]
@aleste8811  la classe user è stata creata puoi iniziare XD

**Comment by bluegrifer00** [comment]
@aleste8811  questa è la versione piu aggiornata se serve altro fammi un fischio

**Comment by agazzarini** [comment]
@bluegrifer00 non ci avevo fatto caso l'altro giorno: occhio ai commenti, a come sono fatti. Guarda la classe InMemoryDatabase (es. : il commento a livello di classe, author va dopo, prima va la descrizione.)

**Comment by bluegrifer00** [comment]
Provvedero 😅
Il giorno 27/mar/2015 10:01, "Andrea Gazzarini" <notifications@github.com>
ha scritto:

**Comment by bluegrifer00** [comment]
@aleste8811
