### ISSUE TITLE
Superclasse  "DomainEntity" per tutti gli oggetti di dominio

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/tcoo#8]
Siccome tutti gli oggetti di dominio (Event, Stand, Location, etc) dovranno essere identificati da un qualcosa di univoco, abbiamo bisogno che tutti abbiano una proprietà di tipo "int" chiamata "id", con relativi getter e setter.

Ora, al fine di evitare di scrivere queste cose su ogni oggetto, è necessario creare una nuova classe di nome DomainEntity (astratta come GeoEntity) che abbia solamente l'attributo int id con getter e setter.

Successivamente bisogna modificare tutte le classi sino ad ora create per far sì che estendano DomainEntity. 

OCCHIO: Alcune classi come Event già estendono una classe, GeoEntity, Siccome in Java l'ereditarietà multipla non è permessa è necessario che ad estendere DomainEntity sia GeoEntity. In questo modo avremo (es)

Event --> GeoEntity --> DomainEntity

Diverso invece per Budget che può direttamente estendere DomainEntity

**Comment by gmm89** [comment]
Ho un po di confusione, ma non è la classe Stand ad estendere GeoEntity?

**Comment by agazzarini** [comment]
azz giusto ho sbagliato, Event non estende niente. Quindi l'esempio che ho fatto sopra era valido per Stand, mentre per Event la relazione è diretta 

class Event extends DomainEntity

**Comment by agazzarini** [comment]
@yurim89 questa si può chiudere giusto?

**Comment by yurim89** [comment]
Si, ma non l'avevamo chiusa venerdì???

Date: Tue, 31 Mar 2015 02:43:36 -0700

**Comment by agazzarini** [comment]
Mi sa di no. Domattin la chiudo, oppure se hai modo chiudila tu
