### ISSUE TITLE
Implementazione classe Location

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/tcoo#9]
La classe Location, che identifica il luogo dove si sovlge l'evento, ha bisogno di altre informazioni. Oltre a quelle che vi possono venire in mente, direi di aggiungere:

- String image: una immagine del posto
- String description: una descrizione del luogo, ad esempio la storia.
- String howToReachUs: descrizione sul come raggiungere il posto dai punti di interesse + vicini (autostrada, treno)  

Tutti con relativi getter e setter. 

Chiaramente, altri attributi che vengono in mente, anche di tipi diversi, sono ben accetti.
Inoltre, essendo la Location un luogo georeferenziabile, deve estendere GeoEntity

**Comment by Ofordo** [comment]
Finish!

**Comment by agazzarini** [comment]
Buono, la classe è ok, metti qualche commento però ;)
